// Product data
export const products = [
  {
    id: 1,
    name: "Modern Comfort Sofa",
    description: "Luxury 3-seater with premium fabric upholstery",
    price: 35999,
    originalPrice: 44999,
    image: "/soap.jpg",
    tag: { text: "Popular", color: "bg-yellow-500" },
  },
  {
    id: 2,
    name: "Elegant Dining Set",
    description: "6-seater wooden dining set with cushioned chairs",
    price: 42999,
    originalPrice: 54999,
    image: "/deepak.jpg",
    tag: { text: "New", color: "bg-green-500" },
  },
  {
    id: 3,
    name: "Modern Study Desk",
    description: "Compact desk with storage and cable management",
    price: 12999,
    originalPrice: 21999,
    image: "/cake.jpg",
    tag: { text: "-40%", color: "bg-blue-500" },
  },
  {
    id: 4,
    name: "Wooden Bedside Table",
    description: "Contemporary design with drawer and open shelf",
    price: 8999,
    originalPrice: 11999,
    image: "/face-kit.jpg",
    tag: { text: "New", color: "bg-green-500" },
  },
  {
    id: 5,
    name: "Wooden Bedside Table",
    description: "Contemporary design with drawer and open shelf",
    price: 8999,
    originalPrice: 11999,
    image: "/face-kit.jpg",
    tag: { text: "New", color: "bg-green-500" },
  },
  {
    id: 6,
    name: "Wooden Bedside Table",
    description: "Contemporary design with drawer and open shelf",
    price: 8999,
    originalPrice: 11999,
    image: "/cake.jpg",
    tag: { text: "New", color: "bg-green-500" },
  },
  {
    id: 7,
    name: "Wooden Bedside Table",
    description: "Contemporary design with drawer and open shelf",
    price: 8999,
    originalPrice: 11999,
    image: "/deepak.jpg",
    tag: { text: "New", color: "bg-green-500" },
  },
  {
    id: 8,
    name: "Wooden Bedside Table",
    description: "Contemporary design with drawer and open shelf",
    price: 8999,
    originalPrice: 11999,
    image: "/soap.jpg",
    tag: { text: "New", color: "bg-green-500" },
  },
];
